// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package lock_configuration

import (
	"context"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcfg "github.com/aws-controllers-k8s/runtime/pkg/config"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackmetrics "github.com/aws-controllers-k8s/runtime/pkg/metrics"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/backup"
	"github.com/go-logr/logr"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &ackv1alpha1.AWSIdentifiers{}
)

type resource struct {
	ko *svcapitypes.LockConfiguration
}

type resourceManager struct {
	cfg          ackcfg.Config
	clientcfg    aws.Config
	log          logr.Logger
	metrics      *ackmetrics.Metrics
	rr           acktypes.Reconciler
	awsAccountID ackv1alpha1.AWSAccountID
	awsRegion    ackv1alpha1.AWSRegion
	sdkapi       *svcsdk.Client
}

// delta holds the result of comparing desired vs. latest sub-resource items.
type delta struct {
	toCreate []*resource
	toUpdate []*resource
	toDelete []*resource
}

// computeDelta performs a key-based diff between the desired and latest
// sub-resource slices.
func computeDelta(desired, latest []resource) delta {
	d := delta{}
	latestMap := make(map[string]*resource)
	for i := range latest {
		latestMap[key(&latest[i])] = &latest[i]
	}

	desiredMap := make(map[string]bool)
	for i := range desired {
		k := key(&desired[i])
		desiredMap[k] = true
		if lat, exists := latestMap[k]; !exists {
			d.toCreate = append(d.toCreate, &desired[i])
		} else {
			rd := newResourceDelta(&desired[i], lat)
			if len(rd.Differences) > 0 {
				d.toUpdate = append(d.toUpdate, &desired[i])
			}
		}
	}

	for k, lat := range latestMap {
		if !desiredMap[k] {
			d.toDelete = append(d.toDelete, lat)
		}
	}
	return d
}

// NewManager creates a resourceManager using the provided SDK client and
// metrics recorder.
func NewManager(
	sdkapi *svcsdk.Client,
	metrics *ackmetrics.Metrics,
) *resourceManager {
	return &resourceManager{
		sdkapi:  sdkapi,
		metrics: metrics,
	}
}

// Sync converts the desired and latest parent resources into internal
// resource slices, computes the diff, and delegates to sync.
func (rm *resourceManager) Sync(
	ctx context.Context,
	desired any,
	latest any,
) (err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.Sync")
	defer func() {
		exit(err)
	}()
	desiredResources := convertToResources(desired)
	latestResources := convertToResources(latest)
	d := computeDelta(desiredResources, latestResources)
	return rm.sync(ctx, d)
}

// convertToResources casts the parent into its concrete type and delegates
// to convertFromParent. Returns nil when the parent has no value at the
// sub-resource's source field.
func convertToResources(parent any) []resource {
	if parent == nil {
		return nil
	}
	v, ok := parent.(*svcapitypes.BackupVault)
	if !ok || v == nil {
		return nil
	}
	if v.Spec.LockConfiguration == nil {
		return nil
	}
	return convertFromParent(v)
}

// The singleton implementation (Get, convertFromParent, sync, key) follows.
// key returns the primary key for a singleton managed field. There is at
// most one managed field per parent, so the key is a constant; this causes
// computeDelta to route value changes through toUpdate instead of
// toCreate+toDelete (which would wipe the item).
func key(r *resource) string {
	_ = r
	return "_singleton"
}

// sync reconciles the singleton managed field. Since there can only be one
// item per parent, computeDelta yields at most one entry in exactly one of
// {toCreate, toUpdate, toDelete}; no iteration or batching is needed.
func (rm *resourceManager) sync(ctx context.Context, d delta) error {
	var err error
	if len(d.toCreate) > 0 {
		_, err = rm.sdkCreate(ctx, d.toCreate[0])
		return err
	}
	if len(d.toUpdate) > 0 {
		_, err = rm.sdkCreate(ctx, d.toUpdate[0])
		return err
	}
	if len(d.toDelete) > 0 {
		_, err = rm.sdkDelete(ctx, d.toDelete[0])
		return err
	}
	return nil
}

// Get reads the current state of the managed field from AWS and writes the
// result back onto the parent's injected spec field.
func (rm *resourceManager) Get(
	ctx context.Context,
	parent *svcapitypes.BackupVault,
) error {
	// Build a minimal seed carrying only the primary key — do NOT use
	// convertFromParent here, because that copies the full desired spec
	// into the seed, which would make latest look identical to desired
	// even when AWS hasn't applied the write yet.
	seed := &resource{ko: &svcapitypes.LockConfiguration{}}
	seed.ko.Spec.BackupVaultName = parent.Spec.Name
	found, err := rm.sdkFind(ctx, seed)
	if err != nil {
		if err == ackerr.NotFound {
			parent.Spec.LockConfiguration = nil
			return nil
		}
		return err
	}
	if found == nil {
		parent.Spec.LockConfiguration = nil
		return nil
	}
	parent.Spec.LockConfiguration = &found.ko.Spec
	return nil
}

// convertFromParent builds a single managed field instance from the parent.
// The parent's injected field is copied wholesale into the managed field Spec,
// then the parent's primary key is written into the managed field's primary
// key field so the SDK call can identify the resource.
func convertFromParent(parent *svcapitypes.BackupVault) []resource {
	ko := &svcapitypes.LockConfiguration{}
	if parent.Spec.LockConfiguration != nil {
		ko.Spec = *parent.Spec.LockConfiguration
	}
	ko.Spec.BackupVaultName = parent.Spec.Name
	return []resource{{ko: ko}}
}

// NewSpecDelta returns a delta comparing two LockConfigurationSpec values.
// The parent resource's delta_pre_compare hook can call this to detect
// changes in the sub-resource's spec fields without duplicating the
// comparison logic.
func NewSpecDelta(
	a *svcapitypes.LockConfigurationSpec,
	b *svcapitypes.LockConfigurationSpec,
) *ackcompare.Delta {
	var ra, rb *resource
	if a != nil {
		ra = &resource{ko: &svcapitypes.LockConfiguration{Spec: *a}}
	}
	if b != nil {
		rb = &resource{ko: &svcapitypes.LockConfiguration{Spec: *b}}
	}
	return newResourceDelta(ra, rb)
}
